@echo off
rem Generated by JetBrains Toolbox 1.16.6319 at Tue Mar 31 15:48:55 2020

start "" C:\Users\Khyber\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\193.6911.25\bin\pycharm64.exe %*

