@echo off
rem Generated by JetBrains Toolbox 1.16.6319 at Sat Apr 11 23:13:31 2020

start "" C:\Users\Khyber\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\193.6911.28\bin\webstorm64.exe %*

