. $FUNCTIONS/bashrc.sh
. $FUNCTIONS/notify.sh
. $FUNCTIONS/alert.sh
. $FUNCTIONS/ring.sh
. $FUNCTIONS/copyAndLink.sh
. $FUNCTIONS/copyReplace.sh
. $FUNCTIONS/path.sh
. $FUNCTIONS/copyLink.sh
. $FUNCTIONS/locateFirst.sh
. $FUNCTIONS/cdLocate.sh
. $FUNCTIONS/gitConvertRemote.sh
. $FUNCTIONS/clone.sh
. $FUNCTIONS/binRust.sh
. $FUNCTIONS/stripRust.sh
. $FUNCTIONS/mvd.sh
. $FUNCTIONS/kudo.sh
. $FUNCTIONS/open.sh
. $FUNCTIONS/ip.sh
. $FUNCTIONS/installPython.sh
. $FUNCTIONS/fopen.sh
. $FUNCTIONS/chrome.sh
. $FUNCTIONS/ls.sh
