. $FUNCTIONS/bashrc.sh
. $FUNCTIONS/copyAndLink.sh
. $FUNCTIONS/copyReplace.sh
. $FUNCTIONS/path.sh
. $FUNCTIONS/copyLink.sh
. $FUNCTIONS/ring.sh
. $FUNCTIONS/locateFirst.sh
. $FUNCTIONS/cdLocate.sh
. $FUNCTIONS/gitConvertRemote.sh
. $FUNCTIONS/clone.sh
