# ip package

name: ip
parent: default

matches:
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          shell: wsl
          cmd: ". /mnt/c/Users/Khyber/workspace/Bash/functions/ip.sh && myip"
