# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":date"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":me"
    replace: "Khyber Sen"

  - trigger: ":github"
    replace: "https://github.com/kkysen"

  - trigger: ":resume"
    replace: "https://github.com/kkysen/me/blob/master/Resume%20-%20Khyber%20Sen.pdf"

  - trigger: ":linkedin"
    replace: ""

  - trigger: ":facebook"
    replace: "https://www.facebook.com/kkysen"

  - trigger: ":fb"
    replace: "https://www.facebook.com/kkysen"
