# Simple package

name: arrows
parent: default

matches:
  - trigger: ":--"
    replace: "—"
  - trigger: ":em"
    replace: "—"
  - trigger: ":en"
    replace: "–"
  - trigger: ":zwsp"
    replace: "<200b>"
  - trigger: ":dot"
    replace: "•"
  - trigger: ":check"
    replace: "✓"
  - trigger: ":sect"
    replace: "§"
  - trigger: ":right"
    replace: "→"
  - trigger: ":left"
    replace: "←"
  - trigger: ":up"
    replace: "↑"
  - trigger: ":down"
    replace: "↓"
  - trigger: ":iff"
    replace: "⟷"
